name: Binance BTC Hourly Fetcher
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install node-fetch@2
      - run: node fetcher.mjs
        env:
          AGG_URL: ${{ secrets.AGG_URL }}
          AGG_PUSH_KEY: ${{ secrets.AGG_PUSH_KEY }}
