name: BTC Hourly Fetcher (multi-source)

on:
  schedule:
    - cron: "0 * * * *"   # chạy mỗi 1h
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run fetcher
        run: node fetcher.mjs
        env:
          AGG_URL: ${{ secrets.AGG_URL }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
